#!/usr/bin/env bash

setup_fnm() {
  local fish_conf_dir="$HOME/.config/fish/conf.d"
  local fish_completions_dir="$HOME/.config/fish/completions"
  local fnm_fish="$fish_conf_dir/fnm.fish"
  local fnm_completion="$fish_completions_dir/fnm.fish"

  command -v fnm >/dev/null 2>&1 || fail "fnm is not installed"

  mkdir -p "$fish_conf_dir"
  mkdir -p "$fish_completions_dir"

  cat > "$fnm_fish" <<'EOF'
# Auto-generated by dotfiles setup
if status is-interactive
  fnm env \
    --use-on-cd \
    --version-file-strategy=recursive \
    --resolve-engines \
    --shell fish | source
end
EOF

  fnm completions --shell=fish > "$fnm_completion"

  log "Created FNM Fish config: $fnm_fish"
  log "Created FNM Fish completions: $fnm_completion"
}

install_latest_node() {
  command -v fnm >/dev/null 2>&1 || fail "fnm is not installed"

  if [[ "${INSTALL_LATEST_NODE:-true}" != "true" ]]; then
    log "Skipping latest Node.js installation"
    return
  fi

  log "Installing latest Node.js through FNM..."
  fnm install --latest

  log "Setting latest Node.js as default..."
  fnm default latest
}
