#!/usr/bin/env bash

detect_brew_bin() {
  if [[ -x "/opt/homebrew/bin/brew" ]]; then
    printf "/opt/homebrew/bin/brew"
  elif [[ -x "/usr/local/bin/brew" ]]; then
    printf "/usr/local/bin/brew"
  elif command -v brew >/dev/null 2>&1; then
    command -v brew
  else
    return 1
  fi
}

install_homebrew() {
  if detect_brew_bin >/dev/null 2>&1; then
    log "Homebrew is already installed"
    return
  fi

  log "Installing Homebrew..."

  NONINTERACTIVE=1 /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

load_homebrew() {
  local brew_bin

  brew_bin="$(detect_brew_bin)" || fail "Homebrew binary is not found"

  eval "$("$brew_bin" shellenv)"

  command -v brew >/dev/null 2>&1 || fail "Homebrew is installed but not available in PATH"

  log "Loaded Homebrew from: $(command -v brew)"
}

install_homebrew_bundle() {
  local brewfile="$DOTFILES_DIR/Brewfile"

  [[ -f "$brewfile" ]] || fail "Brewfile is missing: $brewfile"

  log "Updating Homebrew..."
  brew update && brew upgrade

  log "Installing Homebrew bundle..."
  brew bundle --file="$brewfile"
}

setup_homebrew_for_fish() {
  local fish_conf_dir="$HOME/.config/fish/conf.d"
  local brew_fish="$fish_conf_dir/brew.fish"
  local brew_bin

  brew_bin="$(command -v brew)" || fail "brew is not available"

  mkdir -p "$fish_conf_dir"

  cat > "$brew_fish" <<EOF
# Auto-generated by dotfiles setup
$brew_bin shellenv | source
EOF

  log "Created Homebrew Fish config: $brew_fish"
}
