#!/usr/bin/env bash

HOMEBREW_PACKAGES_TO_INSTALL=(
  fish
  starship
  git
  fnm
)

HOMEBREW_CASKS_TO_INSTALL=(
  font-fira-code-nerd-font
)

detect_brew_bin() {
  if [[ -x "/opt/homebrew/bin/brew" ]]; then
    printf "/opt/homebrew/bin/brew"
  elif [[ -x "/usr/local/bin/brew" ]]; then
    printf "/usr/local/bin/brew"
  elif command -v brew >/dev/null 2>&1; then
    command -v brew
  else
    return 1
  fi
}

install_homebrew() {
  if detect_brew_bin >/dev/null 2>&1; then
    log "Homebrew is already installed"
    return
  fi

  log "Installing Homebrew..."

  NONINTERACTIVE=1 /bin/bash -c \
    "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
}

load_homebrew() {
  local brew_bin

  brew_bin="$(detect_brew_bin)" || fail "Homebrew binary is not found"

  eval "$("$brew_bin" shellenv)"

  command -v brew >/dev/null 2>&1 || fail "Homebrew is installed but not available in PATH"

  log "Loaded Homebrew from: $(command -v brew)"
}

install_homebrew_packages() {
  log "Updating Homebrew..."
  brew update

  for package in "${HOMEBREW_PACKAGES_TO_INSTALL[@]}"; do
    if brew list --formula "$package" >/dev/null 2>&1; then
      log "$package is already installed"
    else
      log "Installing $package..."
      brew install "$package"
    fi
  done
}

install_homebrew_casks() {
  for cask in "${HOMEBREW_CASKS_TO_INSTALL[@]}"; do
    if brew list --cask "$cask" >/dev/null 2>&1; then
      log "$cask is already installed"
    else
      log "Installing $cask..."
      brew install --cask "$cask"
    fi
  done
}

setup_homebrew_for_fish() {
  local fish_conf_dir="$HOME/.config/fish/conf.d"
  local brew_fish="$fish_conf_dir/brew.fish"
  local brew_bin

  brew_bin="$(command -v brew)" || fail "brew is not available"

  mkdir -p "$fish_conf_dir"

  cat > "$brew_fish" <<EOF
# Auto-generated by dotfiles setup
$brew_bin shellenv | source
EOF

  log "Created Homebrew Fish config: $brew_fish"
}
